name: Actions Environment test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: environment

jobs:
  print-environment:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: print-environment-step-1
        env:
          ENVIRONMENT_FLAG: ${{ vars.ENVIRONMENT_FLAG || 'unset' }}
      # environment:
        run: |
          echo "${{ inputs.environment }}"
          echo "ENVIRONMENT_FLAG = $ENVIRONMENT_FLAG"
